FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY tsconfig.json .
COPY . .
RUN npm run build


FROM gcr.io/distroless/nodejs22
WORKDIR /app
COPY --from=build /app/node_modules node_modules
COPY --from=build /app/dist .

ENV PORT=3636

# ENTRYPOINT [ "node" ]
CMD ["./index.js" ]